/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_GAMERPCSERVERSTUB_H_
#define JSONRPC_CPP_STUB_GAMERPCSERVERSTUB_H_

#include <jsonrpccpp/server.h>

class GameRpcServerStub : public jsonrpc::AbstractServer<GameRpcServerStub>
{
    public:
        GameRpcServerStub(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<GameRpcServerStub>(conn, type)
        {
            this->bindAndAddNotification(jsonrpc::Procedure("stop", jsonrpc::PARAMS_BY_NAME,  NULL), &GameRpcServerStub::stopI);
            this->bindAndAddMethod(jsonrpc::Procedure("getcurrentstate", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT,  NULL), &GameRpcServerStub::getcurrentstateI);
        }

        inline virtual void stopI(const Json::Value &request)
        {
            (void)request;
            this->stop();
        }
        inline virtual void getcurrentstateI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->getcurrentstate();
        }
        virtual void stop() = 0;
        virtual Json::Value getcurrentstate() = 0;
};

#endif //JSONRPC_CPP_STUB_GAMERPCSERVERSTUB_H_
