/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_XAYARPCSERVERSTUB_H_
#define JSONRPC_CPP_STUB_XAYARPCSERVERSTUB_H_

#include <jsonrpccpp/server.h>

class XayaRpcServerStub : public jsonrpc::AbstractServer<XayaRpcServerStub>
{
    public:
        XayaRpcServerStub(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<XayaRpcServerStub>(conn, type)
        {
            this->bindAndAddMethod(jsonrpc::Procedure("getzmqnotifications", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_ARRAY,  NULL), &XayaRpcServerStub::getzmqnotificationsI);
            this->bindAndAddNotification(jsonrpc::Procedure("trackedgames", jsonrpc::PARAMS_BY_NAME, "command",jsonrpc::JSON_STRING,"gameid",jsonrpc::JSON_STRING, NULL), &XayaRpcServerStub::trackedgamesI);
            this->bindAndAddMethod(jsonrpc::Procedure("getblockchaininfo", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT,  NULL), &XayaRpcServerStub::getblockchaininfoI);
            this->bindAndAddMethod(jsonrpc::Procedure("getblockhash", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_STRING, "height",jsonrpc::JSON_INTEGER, NULL), &XayaRpcServerStub::getblockhashI);
            this->bindAndAddMethod(jsonrpc::Procedure("game_sendupdates", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "fromblock",jsonrpc::JSON_STRING,"gameid",jsonrpc::JSON_STRING, NULL), &XayaRpcServerStub::game_sendupdatesI);
        }

        inline virtual void getzmqnotificationsI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->getzmqnotifications();
        }
        inline virtual void trackedgamesI(const Json::Value &request)
        {
            this->trackedgames(request["command"].asString(), request["gameid"].asString());
        }
        inline virtual void getblockchaininfoI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->getblockchaininfo();
        }
        inline virtual void getblockhashI(const Json::Value &request, Json::Value &response)
        {
            response = this->getblockhash(request["height"].asInt());
        }
        inline virtual void game_sendupdatesI(const Json::Value &request, Json::Value &response)
        {
            response = this->game_sendupdates(request["fromblock"].asString(), request["gameid"].asString());
        }
        virtual Json::Value getzmqnotifications() = 0;
        virtual void trackedgames(const std::string& command, const std::string& gameid) = 0;
        virtual Json::Value getblockchaininfo() = 0;
        virtual std::string getblockhash(int height) = 0;
        virtual Json::Value game_sendupdates(const std::string& fromblock, const std::string& gameid) = 0;
};

#endif //JSONRPC_CPP_STUB_XAYARPCSERVERSTUB_H_
